#!/usr/bin/env python3

import os
import sys
import shutil

from pathlib import Path

USAGE = """\
ajail - a simple script to make using bubblewrap in a folder easier.

usage: ajail [OPTION]... [<COMMAND>...]

 --fs=<ROOT_FS>     specify the root fs to use. by default uses 'default'. if
                    ROOT_FS is not an absolute path, the name is looked for
                    at ~/.ajail/fs/<ROOT_FS>.
 --ro               wrap the current working directory in a temporary overlay.
 --ro=<SUBDIR>      wrap the provided subdirectory in a temporary overlay.
 --rw=<SUBDIR>      make changes to the provided subdirectory persistent.
 --hide=<SUBDIR>    make the provided subdirectory appear empty.
 --fs-edit          make changes to the root filesystem persistent.
 --no-net           disable network access.

if [<command>...] is not provided, defaults to 'sh'."""

AJAIL_DIR = Path.home() / ".ajail"
FS_DIR = AJAIL_DIR / "fs"

READONLY = 0
READWRITE = 1
HIDEDIR = 2


def nonalnum_replace(s, r):
    return "".join(((c.isalnum() and c or r) for c in s))


def mount_helper(exterior_path, interior_path, mount_type):
    if mount_type == READONLY:
        return [
            "--overlay-src", str(exterior_path),
            "--tmp-overlay", str(interior_path),
        ]
    elif mount_type == READWRITE:
        return [
            "--bind", str(exterior_path), str(interior_path),
        ]
    elif mount_type == HIDEDIR:
        return [
            "--tmpfs", str(interior_path),
        ]
    else:
        raise Exception("unknown mount type %r", mount_type)


def run(fs_to_use, fs_mount, pwd_mount, network, submounts, command):

    if fs_to_use.startswith("/"):
        fs_path = Path(fs_to_use)
    else:
        fs_path = FS_DIR / fs_to_use

    if not fs_path.exists():
        if not FS_DIR.exists():
            print("Error: root fs %r does not exist. please create a rootfs." %
                fs_to_use, file=sys.stderr)
            sys.exit(1)

        if not fs_path.exists():
            print("Error: root fs %r does not exist" % fs_to_use, file=sys.stderr)
            print("Available options: " + (
                ", ".join(repr(d.name) for d in FS_DIR.iterdir() if d.is_dir())
                or "none, please create a rootfs."
            ), file=sys.stderr)
            sys.exit(1)

    if shutil.which("bwrap") is None:
        print("Error: bwrap not found. Please install bubblewrap.",
              file=sys.stderr)
        sys.exit(1)

    bwrap_cmd = [
        "bwrap",
        "--unshare-all",  # default nothing

        # unshare-all only tries on some things. let's explicitly be even more
        # restrictive.
        "--unshare-user",
        "--unshare-cgroup",

        # network access
        (network and "--share-net" or "--unshare-net"),

        # user namespacing
        "--uid", "0",
        "--gid", "0",

        # clear environment
        "--clearenv",
    ]

    # define new environment
    env = {
        "HOME": "/root",
        "PATH": "/root/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
        "TERM": os.environ.get("TERM", "xterm"),
    }

    for name, val in os.environ.items():
        if name.startswith("AJAIL_ENV_"):
            env[name.removeprefix("AJAIL_ENV_")] = val

    for name, val in env.items():
        bwrap_cmd.extend(["--setenv", name, val])

    # mount root
    bwrap_cmd.extend(mount_helper(fs_path, "/", fs_mount))

    # essential mounts
    bwrap_cmd.extend([
        "--dev", "/dev",
        "--proc", "/proc",
        "--tmpfs", "/tmp",
        "--tmpfs", "/run",
    ])

    if network:
        bwrap_cmd.extend([
            "--ro-bind", "/etc/resolv.conf", "/etc/resolv.conf",
        ])

    pwd = Path.cwd()

    # mount pwd
    bwrap_cmd.extend(mount_helper(pwd, pwd, pwd_mount))

    # mount submounts
    for mount_type, path in submounts:
        subpath = pwd / path
        bwrap_cmd.extend(mount_helper(subpath, subpath, mount_type))

    bwrap_cmd.extend([
        # set hostname
        "--hostname", "ajail-" + nonalnum_replace(fs_to_use, "-"),

        # start in pwd
        "--chdir", str(pwd),

        "--"
    ])

    bwrap_cmd.extend(command)

    os.execvp(bwrap_cmd[0], bwrap_cmd)
    raise Exception("unreachable")


def main():
    args = sys.argv[1:]

    fs_to_use = os.environ.get("AJAIL_FS", "default")
    fs_mount = READONLY
    pwd_mount = READWRITE
    network = True
    submounts = []
    command = []

    while args:
        arg = args[0]

        if arg.startswith("--"):
            arg = arg[1:]

        if arg.startswith("-fs="):
            fs_to_use = arg.removeprefix("-fs=")

        elif arg == "-ro":
            pwd_mount = READONLY

        elif arg.startswith("-ro="):
            submounts.append((READONLY, arg.removeprefix("-ro=")))
        elif arg.startswith("-rw="):
            submounts.append((READWRITE, arg.removeprefix("-rw=")))
        elif arg.startswith("-hide="):
            submounts.append((HIDEDIR, arg.removeprefix("-hide=")))

        elif arg == "-fs-edit":
            fs_mount = READWRITE

        elif arg == "-no-net":
            network = False

        elif arg == "-":
            command = args[1:]
            break

        elif arg.startswith("-"):
            print(USAGE)
            sys.exit(1)

        else:
            command = args
            break

        args = args[1:]

    if not command:
        command = ["sh"]

    run(fs_to_use=fs_to_use, fs_mount=fs_mount, pwd_mount=pwd_mount,
        network=network, submounts=submounts, command=command)
    raise Exception("unreachable")


if __name__ == "__main__":
    main()
