#!/usr/bin/env python3

import os
import sys
import shutil
import tempfile

from pathlib import Path
from datetime import datetime

USAGE = """\
ajail - a simple script to make using bubblewrap in a folder easier.

usage: ajail [OPTION]... [<COMMAND>...]

 --fs=<ROOT_FS>           specify the root fs to use. by default uses 'default'.
                          if ROOT_FS is not an absolute path, the name is looked
                          for at ~/.ajail/fs/<ROOT_FS>.
 --ro[=<DIR>]             wrap the provided directory in a temporary overlay.
                          if no directory is specified, cwd is assumed.
 --rw[=<DIR>]             make changes to the provided directory persistent.
 --hide[=<DIR>]           make the provided directory appear empty.
 --mount=<SRC>,<DST>[,rw] mount SRC at DST. mounted with a temporary overlay
                          unless rw is provided for persistence.
 --fs-edit[=<DIR>]        make changes to the root filesystem persistent. if
                          <DIR> is provided, just that subtree.
 --home-edit[=<SUBDIR>]   a subset of --fs-edit, make just jail-home changes
                          persistent, optionally just a subdirectory.
 --no-net                 disable network access.
 --clone                  if the current directory is a source repository,
                          instead of mounting the current directory directly,
                          we will make a new clone of the source repository,
                          and mount that. pushing from inside will update the
                          current directory's metadata.
 --quiet                  no status output

if [<command>...] is not provided, defaults to 'sh'."""

AJAIL_DIR = Path.home() / ".ajail"
FS_DIR = AJAIL_DIR / "fs"
READONLY, READWRITE, HIDEDIR, SKIPMOUNT = 1, 2, 3, 4


def nonalnum_replace(s, r):
    return "".join(c if c.isalnum() else r for c in s)


def mount_helper(exterior_path, interior_path, mount_type, show_status):
    exterior_path = str(Path(exterior_path).absolute())
    interior_path = str(Path(interior_path).absolute())
    mounts = {
        READONLY: ["--overlay-src", exterior_path, "--tmp-overlay", interior_path],
        READWRITE: ["--bind", exterior_path, interior_path],
        HIDEDIR: ["--tmpfs", interior_path],
    }
    if mount_type not in mounts:
        raise Exception("unknown mount type: %r" % mount_type)
    if show_status:
        print("  %s -> %s (%s)" % (
            exterior_path if mount_type != HIDEDIR else "_",
            interior_path, "rw" if mount_type == READWRITE else "ro"))
    return mounts[mount_type]


def clone_repo(fs_to_use, pwd):
    # make directory for independent clone
    clone_base = AJAIL_DIR / "clone"
    os.makedirs(str(clone_base), exist_ok=True)
    clone_dir = Path(tempfile.mkdtemp(
        dir=str(clone_base),
        prefix="%s-%s-" % (
            nonalnum_replace(str(pwd), '_'),
            datetime.now().strftime("%Y%m%d"))))

    # clone current .git to new directory inside a jail
    child = os.fork()
    if child == 0:
        os.chdir(clone_dir)
        run(fs_to_use=fs_to_use, pwd_type=READWRITE, network=False, fs_edits=[],
            submounts=[(READONLY, str(pwd / ".git"), "/ajail/origin")],
            command=["git", "clone", "-q", "/ajail/origin", "."])
        raise Exception("unreachable")

    # wait for clone
    _, status = os.waitpid(child, 0)
    if not os.WIFEXITED(status) or os.WEXITSTATUS(status) != 0:
        print(f"Clone failed: {status}.", file=sys.stderr)
        sys.exit(1)

    return clone_dir


def run(fs_to_use, pwd_type, network, submounts, fs_edits, command,
        clone=False, env_override=False, show_status=False):

    if fs_to_use.startswith("/"):
        fs_path = Path(fs_to_use)
    else:
        fs_path = FS_DIR / fs_to_use

    if not fs_path.exists():
        print("Error: root fs %r does not exist." % fs_to_use, file=sys.stderr)
        options = ""
        if FS_DIR.exists():
            options = ", ".join(
                repr(d.name) for d in FS_DIR.iterdir() if d.is_dir())
        if options:
            print("Available: " + options, file=sys.stderr)
        else:
            print("Please create a rootfs.", file=sys.stderr)
        sys.exit(1)

    if shutil.which("bwrap") is None:
        print("Error: bwrap not found. Please install bubblewrap.",
              file=sys.stderr)
        sys.exit(1)

    pwd = Path.cwd()

    if clone and not (pwd / ".git").exists():
        print("Error: clone mode only works with git repos right now.",
              file=sys.stderr)
        sys.exit(1)

    bwrap_cmd = [
        "bwrap",
        "--unshare-all",  # default nothing

        # unshare-all only tries on some things. let's explicitly be even more
        # restrictive.
        "--unshare-user", "--unshare-cgroup",

        # network access
        "--share-net" if network else "--unshare-net",

        # user namespacing
        "--uid", "0", "--gid", "0",

        # clear environment
        "--clearenv",
    ]

    # define new environment
    env = {
        "HOME": "/root",
        "PATH": ("/root/.local/bin:/usr/local/sbin:/usr/local/bin:"
                 "/usr/sbin:/usr/bin:/sbin:/bin"),
        "TERM": os.environ.get("TERM", "xterm"),
        "IS_SANDBOX": "1",
    }

    if env_override:
        for name, val in os.environ.items():
            if name.startswith("AJAIL_ENV_"):
                env[name.removeprefix("AJAIL_ENV_")] = val

    for name, val in env.items():
        bwrap_cmd.extend(["--setenv", name, val])

    if show_status:
        print("ajail %s in %s" % (fs_to_use, str(pwd)))
        print("Networking:", "enabled" if network else "disabled")
        print("Mounts:")

    # mount root
    if "/" in fs_edits:
        bwrap_cmd.extend(mount_helper(fs_path, "/", READWRITE, show_status))
    else:
        bwrap_cmd.extend(mount_helper(fs_path, "/", READONLY, show_status))
        for path in fs_edits:
            bwrap_cmd.extend(mount_helper(str(fs_path) + path, path, READWRITE, show_status))

    # essential mounts
    bwrap_cmd.extend([
        "--dev", "/dev",
        "--proc", "/proc",
        "--tmpfs", "/tmp",
        "--tmpfs", "/run",
    ])

    if network:
        bwrap_cmd.extend([
            "--ro-bind", "/etc/resolv.conf", "/etc/resolv.conf",
        ])

    if clone and pwd_type in (READONLY, READWRITE):
        if show_status:
            print("  (Cloning new independent workspace...)")

        clone_dir = clone_repo(fs_to_use=fs_to_use, pwd=pwd)
        bwrap_cmd.extend(mount_helper(pwd / ".git", "/ajail/origin", pwd_type, show_status))
        bwrap_cmd.extend(mount_helper(clone_dir, pwd, pwd_type, show_status))

    else:
        bwrap_cmd.extend(mount_helper(pwd, pwd, pwd_type, show_status))

    # mount submounts
    for mount_type, src, dest in submounts:
        bwrap_cmd.extend(mount_helper(src, dest, mount_type, show_status))

    bwrap_cmd.extend([
        # set hostname
        "--hostname", "ajail-" + nonalnum_replace(fs_to_use, "-"),

        # start in pwd if mounted
        "--chdir", str(pwd),

        "--"
    ])

    bwrap_cmd.extend(command)

    if show_status:
        print("Starting...\n")

    os.execvp(bwrap_cmd[0], bwrap_cmd)
    raise Exception("unreachable")


def main():
    args = sys.argv[1:]
    if os.environ.get("AJAIL_ARGS", ""):
        args = os.environ.get("AJAIL_ARGS").split(";") + args

    fs_to_use = "default"
    pwd_type = READWRITE
    clone, show_status = False, True
    network = True
    submounts, fs_edits = [], []
    command = []

    # tight control over argument parsing
    while args:
        arg = args[0]
        if arg.startswith("--"):
            arg = arg[1:]

        if arg.startswith("-fs="):
            fs_to_use = arg.removeprefix("-fs=")

        elif arg in ("-ro", "-rw", "-hide"):
            pwd_type = {"-ro": READONLY, "-rw": READWRITE, "-hide": HIDEDIR}[arg]

        elif arg.startswith("-ro="):
            arg = arg.removeprefix("-ro=")
            submounts.append((READONLY, arg, arg))
        elif arg.startswith("-rw="):
            arg = arg.removeprefix("-rw=")
            submounts.append((READWRITE, arg, arg))
        elif arg.startswith("-hide="):
            arg = arg.removeprefix("-hide=")
            submounts.append((HIDEDIR, "", arg))
        elif arg.startswith("-mount="):
            parts = arg.removeprefix("-mount=").split(",")
            if len(parts) == 2:
                submounts.append((READONLY, parts[0], parts[1]))
            elif len(parts) == 3 and parts[2] in ("ro", "rw"):
                submounts.append((
                    READWRITE if parts[2] == "rw" else READONLY,
                    parts[0], parts[1]))
            else:
                print(USAGE)
                sys.exit(1)

        elif arg == "-fs-edit" or arg.startswith("-fs-edit="):
            fs_edits.append("/" + arg.removeprefix("-fs-edit").removeprefix("=").removeprefix("/"))
        elif arg == "-home-edit" or arg.startswith("-home-edit="):
            fs_edits.append("/root/" + arg.removeprefix("-home-edit").removeprefix("="))

        elif arg == "-no-net":
            network = False
        elif arg == "-clone":
            clone = True
        elif arg == "-quiet":
            show_status = False

        elif arg == "-":
            command = args[1:]
            break

        elif arg.startswith("-"):
            print(USAGE)
            sys.exit(1)

        else:
            command = args
            break

        args = args[1:]

    if not command:
        command = ["sh"]

    run(fs_to_use=fs_to_use, pwd_type=pwd_type, network=network,
        submounts=submounts, fs_edits=fs_edits, command=command, clone=clone,
        env_override=True, show_status=show_status)
    raise Exception("unreachable")


if __name__ == "__main__":
    main()
